### Get all credentials
GET http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}

### Get single credential
GET http://localhost:3000/api/credentials/google
Authorization: {{$dotenv MASTERPASSWORD}}

### Add single credential
POST http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}
Content-Type: application/json

{
    "service": "Instagram",
    "username": "Magda",
    "password": "13874618"
}

### Delete single credential
DELETE http://localhost:3000/api/credentials/....


### Modify existing credential
PATCH http://localhost:3000/api/credentials/....
Authorization: {{$dotenv MASTERPASSWORD}}
Content-Type: application/json

{
    "service": "StudiVZ",
    "username": "Magda",
    "password": "alterfisch"
}